//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kundt_front_end.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAuto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAuto()
        {
            this.tblBuchung = new HashSet<tblBuchung>();
            this.tblAusstattung = new HashSet<tblAusstattung>();
        }
    
        public int IDAuto { get; set; }
        public short Baujahr { get; set; }
        public string PS { get; set; }
        public string Getriebe { get; set; }
        public string Tueren { get; set; }
        public byte Sitze { get; set; }
        public decimal MietPreis { get; set; }
        public decimal VerkaufPreis { get; set; }
        public decimal Kilometerstand { get; set; }
        public byte[] AutoBild { get; set; }
        public bool Anzeigen { get; set; }
        public int FKTreibstoff { get; set; }
        public int FKTyp { get; set; }
        public int FKKategorie { get; set; }
    
        public virtual tblKategorie tblKategorie { get; set; }
        public virtual tblTreibstoff tblTreibstoff { get; set; }
        public virtual tblTyp tblTyp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBuchung> tblBuchung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAusstattung> tblAusstattung { get; set; }
    }
}
