//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kundt_front_end.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEyecatcher
    {
        public int IDEyecatcher { get; set; }
        public System.Guid GUIDBild { get; set; }
        public byte[] Eyecatcher { get; set; }
    }
}
