//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kundt_front_end.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHistorie
    {
        public int IDHistorie { get; set; }
        public int FKMitarbeiter { get; set; }
        public int FKBuchung { get; set; }
        public System.DateTime AenderungsDatum { get; set; }
    
        public virtual tblBuchung tblBuchung { get; set; }
        public virtual tblMitarbeiter tblMitarbeiter { get; set; }
    }
}
