//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kundt_front_end.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKunde
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKunde()
        {
            this.tblBuchung = new HashSet<tblBuchung>();
        }
    
        public int IDKunde { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public string Strasse { get; set; }
        public string Telefon { get; set; }
        public string Anrede { get; set; }
        public System.DateTime GebDatum { get; set; }
        public string ReisepassNr { get; set; }
        public Nullable<int> FKPLZOrt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBuchung> tblBuchung { get; set; }
        public virtual tblPLZOrt tblPLZOrt { get; set; }
        public virtual tblLogin tblLogin { get; set; }
    }
}
