//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kundt_front_end.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogin
    {
        public int IDLogin { get; set; }
        public string Email { get; set; }
        public string Passwort { get; set; }
        public string Rolle { get; set; }
        public bool Deaktiviert { get; set; }
    
        public virtual tblKunde tblKunde { get; set; }
        public virtual tblMitarbeiter tblMitarbeiter { get; set; }
    }
}
